bosh deploy -d concourse concourse.yml \
  -l ../versions.yml \
  -l "/tmp/env-stage-internal-pcf/vars/director-vars-store.yml" \
  --vars-store cluster-creds.yml \
  -o operations/basic-auth.yml \
  -o operations/privileged-http.yml \
  -o operations/privileged-https.yml \
  -o operations/tls.yml \
  -o operations/tls-vars.yml \
  -o operations/web-network-extension.yml \
  -o operations/credhub.yml \
  -o operations/worker-ephemeral-disk.yml \
  --var network_name=default \
  --var web_vm_type=default \
  --var db_vm_type=default \
  --var db_persistent_disk_type=10GB \
  --var worker_vm_type=default \
  --var deployment_name=concourse \
  --var web_network_name=private \
  --var web_network_vm_extension=ilb \
  --var atc_basic_auth.username=<CHANGE> \
  --var atc_basic_auth.password=<CHANGE> \
  --var external_url=https://<CHANGE>
  --var worker_ephemeral_disk=500GB_ephemeral_disk
