---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: pcf-pipelines
- name: terraform-state

outputs:
- name: wipe-output

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:
  GCP_RESOURCE_PREFIX:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_ZONE:

run:
  path: pcf-pipelines/install-pcf/gcp/tasks/wipe-env/task.sh
