---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OM_DECRYPTION_PWD:

inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/config-opsman/task.sh
