platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


params:
  ATC_EXTERNAL_URL:
  ATC_BASIC_AUTH_USERNAME:
  ATC_BASIC_AUTH_PASSWORD:
  ATC_TEAM_NAME:

run:
  path: bash
  args:
  - -ce
  - |
    curl \
      --silent \
      --insecure \
      --output fly \
      "${ATC_EXTERNAL_URL}/api/v1/cli?arch=amd64&platform=linux"

    chmod +x fly

    ./fly --target self login \
      --insecure \
      --concourse-url "${ATC_EXTERNAL_URL}" \
      --username "${ATC_BASIC_AUTH_USERNAME}" \
      --password "${ATC_BASIC_AUTH_PASSWORD}" \
      --team-name "${ATC_TEAM_NAME}"

    buildpacks=(
      go
      tcserver
      php
      java
      ruby
      binary
      nodejs
      python
      staticfile
      dotnet
    )

    for buildpack in "${buildpacks[@]}"; do
      for step in stage promote; do
        ./fly --target self trigger-job \
          --job lre1-aws-buildpacks-upgrade/$step-$buildpack-buildpack \
          --watch
      done
    done
