---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: unpatched-release
  - name: pcf-pipelines
outputs:
  - name: patched-release

run:
  path: pcf-pipelines/ci/tasks/apply-rc-pipelines-patches/task.sh
