# Params for an S3-compatible repository
s3_access_key_id:
s3_secret_access_key:
s3_endpoint:
s3_bucket:
# URL to the airgapped concourse server
atc_external_url:
atc_basic_auth_username:
atc_basic_auth_password:
atc_team_name:
# Name of the pipeline
rc_offline_pipeline_name:
# Params for the install-pcf pipeline, appropriately indented, e.g.
#
# rc_offline_vsphere_install_params: |
#     pivnet_token: ...
#     opsman_domain_or_ip_address: ...
# ...
#
rc_offline_vsphere_install_params:
# Private key to decrypt the final tarball
# https://help.github.com/articles/generating-a-new-gpg-key/
gpg_private_key_contents:
